modift nano 2.4inch driver

diff --git a/NANO24-show b/NANO24-show
--- a/NANO24-show
+++ b/NANO24-show
@@ -22,6 +22,11 @@ sudo echo "dtparam=spi=on" >> ./boot/config.txt.bak
 sudo echo "enable_uart=1" >> ./boot/config.txt.bak
 sudo echo "dtoverlay=tft7789:rotate=90" >> ./boot/config.txt.bak
 sudo echo "dtoverlay=ft6236" >> ./boot/config.txt.bak
+sudo echo "hdmi_group=2" >> ./boot/config.txt.bak
+sudo echo "hdmi_mode=1" >> ./boot/config.txt.bak
+sudo echo "hdmi_mode=87" >> ./boot/config.txt.bak
+sudo echo "hdmi_cvt 320 240 60 6 0 0 0" >> ./boot/config.txt.bak
+sudo echo "hdmi_drive=2" >> ./boot/config.txt.bak
 sudo echo "gpio=18=op,dh" >> ./boot/config.txt.bak
 sudo cp -rf ./boot/config.txt.bak /boot/config.txt
 
@@ -35,9 +40,44 @@ sudo cp -rf ./usr/99-fbturbo.conf  /usr/share/X11/xorg.conf.d/99-fbturbo.conf
 #sudo cp ./usr/cmdline.txt /boot/
 #fi
 sudo cp ./usr/inittab /etc/
-#sudo cp ./boot/config-32.txt /boot/config.txt
 sudo touch ./.have_installed
 echo "gpio:resistance:nano24:90:320:240" > ./.have_installed
+
+#FBCP install
+wget --spider -q -o /dev/null --tries=1 -T 10 https://cmake.org/
+if [ $? -eq 0 ]; then
+sudo apt-get install cmake -y 2> error_output.txt
+result=`cat ./error_output.txt`
+echo -e "\033[31m$result\033[0m"
+grep -q "^E:" ./error_output.txt
+type cmake > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+sudo rm -rf rpi-fbcp
+wget --spider -q -o /dev/null --tries=1 -T 10 https://github.com
+if [ $? -eq 0 ]; then
+sudo git clone https://github.com/tasanakorn/rpi-fbcp
+else
+echo "bad network, copy native fbcp!!!"
+sudo cp -r ./usr/rpi-fbcp .
+fi
+sudo mkdir ./rpi-fbcp/build
+cd ./rpi-fbcp/build/
+sudo cmake ..
+sudo make
+sudo install fbcp /usr/local/bin/fbcp
+cd - > /dev/null
+type fbcp > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+sudo cp -rf ./usr/99-fbturbo-fbcp.conf  /usr/share/X11/xorg.conf.d/99-fbturbo.conf
+sudo cp -rf ./etc/rc.local /etc/rc.local
+fi
+else
+echo "install cmake error!!!!"
+fi
+else
+echo "bad network, can't install cmake!!!"
+fi
+
 #evdev install
 #nodeplatform=`uname -n`
 #kernel=`uname -r`
